config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-auburn-falcon.sh
        container: qc.acc_squirrely-wheat-peccary
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-plum-ostrich.sh
        container: qc.doc_hazy-sepia-mayfly
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-azure-frise.sh
        container: qc.doc_dorky-orchid-kudu
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-eggplant-meerkat.sh
        container: qc.doc_stuffy-linen-civet
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-turquoise-gibbon.sh
        container: qc.lic_slaphappy-coral-squirt
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-emerald-dingo.sh
        container: qc.sec_lousy-celadon-hare
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mustard-tamarin.sh
        container: qc.sty_snazzy-lemon-schnauzer
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-orchid-butterfly.sh
        container: qc.ver_flaky-orchid-ladybird
timeout: 5400
