config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-mustard-orangutan.sh
        container: qc.acc_bumpy-aqua-bongo
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cardinal-indri.sh
        container: qc.doc_beady-vermilion-gerbil
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pumpkin-moose.sh
        container: qc.doc_shaggy-asparagus-bee
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-amethyst-axolotl.sh
        container: qc.doc_goopy-mauve-coyote
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-carmine-koala.sh
        container: qc.lic_smelly-heliotrope-capuchin
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-russet-tortoise.sh
        container: qc.sec_bluesy-indigo-centipede
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-burgundy-birman.sh
        container: qc.sty_hilly-magenta-rabbit
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-buff-buffalo.sh
        container: qc.ver_stuffy-apricot-sheepdog
timeout: 5400
