config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cerulean-orangutan.sh
        container: qc.acc_cozy-mauve-wallaby
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-magnolia-dolphin.sh
        container: qc.doc_randy-saffron-caterpillar
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-aquamarine-octopus.sh
        container: qc.doc_whiny-aqua-woodpecker
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-chartreuse-albatross.sh
        container: qc.doc_wimpy-beige-mule
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-red-wasp.sh
        container: qc.lic_slimy-zucchini-zorse
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-green-crane.sh
        container: qc.sec_messy-seashell-dhole
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-saffron-centipede.sh
        container: qc.sty_pasty-razzmatazz-vulture
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-blue-lobster.sh
        container: qc.ver_slimy-ivory-collie
timeout: 5400
