config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-silver-terrier.sh
        container: qc.acc_snappy-rose-lizard
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-xanthic-birman.sh
        container: qc.doc_stealthy-corn-alligator
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lime-mayfly.sh
        container: qc.doc_chummy-blue-monster
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-crimson-newt.sh
        container: qc.doc_snoopy-tomato-termite
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ochre-labradoodle.sh
        container: qc.lic_slimy-seashell-markhor
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-persimmon-dolphin.sh
        container: qc.sec_geeky-wisteria-snail
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-goldenrod-mau.sh
        container: qc.sty_lumpy-orchid-harrier
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ochre-wasp.sh
        container: qc.ver_crappy-silver-dalmatian
timeout: 5400
